(cl:defpackage ilqr_loco-msg
  (:use )
  (:export
   "<TRAJEXECFEEDBACK>"
   "TRAJEXECFEEDBACK"
   "<TRAJEXECACTIONRESULT>"
   "TRAJEXECACTIONRESULT"
   "<TRAJEXECGOAL>"
   "TRAJEXECGOAL"
   "<TRAJEXECACTIONGOAL>"
   "TRAJEXECACTIONGOAL"
   "<TRAJEXECACTIONFEEDBACK>"
   "TRAJEXECACTIONFEEDBACK"
   "<TRAJEXECACTION>"
   "TRAJEXECACTION"
   "<TRAJEXECRESULT>"
   "TRAJEXECRESULT"
  ))

