// Generated by gencpp from file ilqr_loco/TrajExecFeedback.msg
// DO NOT EDIT!


#ifndef ILQR_LOCO_MESSAGE_TRAJEXECFEEDBACK_H
#define ILQR_LOCO_MESSAGE_TRAJEXECFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ilqr_loco
{
template <class ContainerAllocator>
struct TrajExecFeedback_
{
  typedef TrajExecFeedback_<ContainerAllocator> Type;

  TrajExecFeedback_()
    : step(0)  {
    }
  TrajExecFeedback_(const ContainerAllocator& _alloc)
    : step(0)  {
  (void)_alloc;
    }



   typedef int32_t _step_type;
  _step_type step;




  typedef boost::shared_ptr< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TrajExecFeedback_

typedef ::ilqr_loco::TrajExecFeedback_<std::allocator<void> > TrajExecFeedback;

typedef boost::shared_ptr< ::ilqr_loco::TrajExecFeedback > TrajExecFeedbackPtr;
typedef boost::shared_ptr< ::ilqr_loco::TrajExecFeedback const> TrajExecFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ilqr_loco

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'ilqr_loco': ['/home/ubuntu/catkin_ws/devel/share/ilqr_loco/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'loco_msgs': ['/home/ubuntu/catkin_ws/src/loco_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99174260c0c07917ce2b7a46302ab7a8";
  }

  static const char* value(const ::ilqr_loco::TrajExecFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99174260c0c07917ULL;
  static const uint64_t static_value2 = 0xce2b7a46302ab7a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilqr_loco/TrajExecFeedback";
  }

  static const char* value(const ::ilqr_loco::TrajExecFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32 step\n\
\n\
";
  }

  static const char* value(const ::ilqr_loco::TrajExecFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrajExecFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilqr_loco::TrajExecFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilqr_loco::TrajExecFeedback_<ContainerAllocator>& v)
  {
    s << indent << "step: ";
    Printer<int32_t>::stream(s, indent + "  ", v.step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILQR_LOCO_MESSAGE_TRAJEXECFEEDBACK_H
