// Generated by gencpp from file ilqr_loco/TrajExecResult.msg
// DO NOT EDIT!


#ifndef ILQR_LOCO_MESSAGE_TRAJEXECRESULT_H
#define ILQR_LOCO_MESSAGE_TRAJEXECRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ilqr_loco
{
template <class ContainerAllocator>
struct TrajExecResult_
{
  typedef TrajExecResult_<ContainerAllocator> Type;

  TrajExecResult_()
    : done(false)  {
    }
  TrajExecResult_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;




  typedef boost::shared_ptr< ::ilqr_loco::TrajExecResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilqr_loco::TrajExecResult_<ContainerAllocator> const> ConstPtr;

}; // struct TrajExecResult_

typedef ::ilqr_loco::TrajExecResult_<std::allocator<void> > TrajExecResult;

typedef boost::shared_ptr< ::ilqr_loco::TrajExecResult > TrajExecResultPtr;
typedef boost::shared_ptr< ::ilqr_loco::TrajExecResult const> TrajExecResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilqr_loco::TrajExecResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ilqr_loco

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'ilqr_loco': ['/home/ubuntu/catkin_ws/devel/share/ilqr_loco/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'loco_msgs': ['/home/ubuntu/catkin_ws/src/loco_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilqr_loco::TrajExecResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilqr_loco::TrajExecResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilqr_loco::TrajExecResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::ilqr_loco::TrajExecResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilqr_loco/TrajExecResult";
  }

  static const char* value(const ::ilqr_loco::TrajExecResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool done\n\
";
  }

  static const char* value(const ::ilqr_loco::TrajExecResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrajExecResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilqr_loco::TrajExecResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilqr_loco::TrajExecResult_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILQR_LOCO_MESSAGE_TRAJEXECRESULT_H
